<?php

namespace AppBundle\Repository;

/**
 * ApiItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
